name: CI
on: [push]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - run: pip install poetry
    - name: install dependencies
      run: poetry install
    - name: Lint
      run: make lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - run: pip install poetry
    - name: install dependencies
      run: poetry install
    - run: make test_with_coverage
      name: test

  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI 
    needs: [test, lint]
    if: ${{ github.ref_name == 'master' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - run: pip install poetry
    - name: Bump patch version
      run: poetry version patch
    - uses: EndBug/add-and-commit@v7
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'bump version'
        push: true
    - run: poetry build
    - name: Publish distribution ğŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
